/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframeaula;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author 1017729
 */
public class PesoPlanetas extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PesoPlanetas.class.getName());

    /**
     * Creates new form PesoPlanetas
     */
    public PesoPlanetas() {
        initComponents();
    }

    public String calculoPeso(double gravidade) {
        
        String StrpesoTerra = jTPesoTerra.getText();
        StrpesoTerra = converterVirgula(StrpesoTerra);
        
        double pesoTerra = Double.parseDouble(StrpesoTerra);
        
        double pesoPlaneta = (pesoTerra / 9.8) * gravidade;
        return limitarDecimal(pesoPlaneta);
        
        
        
    }
    
    public String limitarDecimal(double valor){
        DecimalFormat df = new DecimalFormat("#.##");
        
        String valorTratado = df.format(valor);

        return valorTratado;
    }
    
    public String converterVirgula(String valor){
        String valorConvertido = valor.replace(",", ".");
        
        return valorConvertido;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTPesoTerra = new javax.swing.JTextField();
        jMenuPlanetas = new javax.swing.JComboBox<>();
        jCalcularPeso = new javax.swing.JButton();
        jTPesoPlaneta = new javax.swing.JTextField();

        jLabel1.setText("jLabel1");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Peso na Terra(Kg)");

        jTPesoTerra.addActionListener(this::jTPesoTerraActionPerformed);

        jMenuPlanetas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jMenuPlanetas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mercúrio", "Vênus", "Terra", "Marte", "Júpiter", "Saturno", "Urano", "Netuno", "Lua" }));
        jMenuPlanetas.setBorder(null);
        jMenuPlanetas.addActionListener(this::jMenuPlanetasActionPerformed);

        jCalcularPeso.setText("Calcular Peso");
        jCalcularPeso.addActionListener(this::jCalcularPesoActionPerformed);

        jTPesoPlaneta.addActionListener(this::jTPesoPlanetaActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(jTPesoTerra))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jMenuPlanetas, 0, 187, Short.MAX_VALUE)
                    .addComponent(jTPesoPlaneta))
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jCalcularPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jMenuPlanetas, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTPesoTerra)
                    .addComponent(jTPesoPlaneta))
                .addGap(50, 50, 50)
                .addComponent(jCalcularPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTPesoTerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPesoTerraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPesoTerraActionPerformed

    private void jTPesoPlanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTPesoPlanetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTPesoPlanetaActionPerformed

    private void jCalcularPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCalcularPesoActionPerformed
        // TODO add your handling code here:   

        String planeta = jMenuPlanetas.getSelectedItem().toString();
        double gravidade = 0.0;

        switch (planeta) {
            case "Mercúrio":
                gravidade = 3.6;
                break;
            case "Vênus":
                gravidade = 8.7;
                break;
            case "Terra":
                gravidade = 9.8;
                break;
            case "Marte":
                gravidade = 3.7;
                break;
            case "Júpiter":
                gravidade = 24.79;
                break;
            case "Saturno":
                gravidade = 10.44;
                break;
            case "Urano":
                gravidade = 8.69;
                break;
            case "Netuno":
                gravidade = 11.15;
                break;
            case "Lua":
                gravidade = 1.6;
                break;
            default:
                JOptionPane.showMessageDialog(null, "Erro na seleção de planetas");
        }

        
        try {
        jTPesoPlaneta.setText(String.valueOf(calculoPeso(gravidade)));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite um valor inteiro");
        }
        
    }//GEN-LAST:event_jCalcularPesoActionPerformed

    private void jMenuPlanetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPlanetasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuPlanetasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PesoPlanetas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCalcularPeso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JComboBox<String> jMenuPlanetas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTPesoPlaneta;
    private javax.swing.JTextField jTPesoTerra;
    // End of variables declaration//GEN-END:variables
}
